Repository M-S-projects/Christmast, pull requests merged in 2023-12, with the labels that each got.

#2 :lipstick: : update Background Template Comp
  package.json
  src/App.tsx
  src/components/.gitkeep
  src/components/Background/index.tsx
  src/components/Background/style.ts
  yarn.lock
Labels: 🎨 Type: Publishing

#4 :sparkles: :트리 데이터 불러오기
  .gitignore
  src/App.tsx
  src/pages/tree/index.tsx
Labels: ✨Type: feat

#5 Promotion 페이지, Background 컴포넌트 퍼블리싱
  .env
  package-lock.json
  src/API/index.ts
  src/API/tokenmanager.ts
  src/App.tsx
  src/components/Background/index.tsx
  src/components/Background/style.ts
  src/components/Input/input.tsx
  src/components/Input/style.ts
  src/pages/commentPost/index.tsx
  src/pages/commentPost/style.ts
  src/pages/login/index.tsx
  src/pages/login/style.ts
  src/pages/promotion/index.tsx
  src/pages/promotion/style.ts
  src/pages/register/index.tsx
  src/style.ts
  src/style/globals.tsx
  src/types/CommentType.ts
  src/types/InputProps.ts
  src/types/LoginType.ts
Labels: 🎨 Type: Publishing

#7 로그인 페이지 퍼블리싱
  package.json
  src/components/Background/style.ts
  src/pages/register/index.tsx
  src/pages/register/style.ts
  yarn.lock
Labels: 🎨 Type: Publishing

#9 트리페이지 퍼블리싱
  src/App.tsx
  src/assets/svgs/Arrow.tsx
  src/assets/svgs/Bell.tsx
  src/assets/svgs/Candy.tsx
  src/assets/svgs/CommentTree.tsx
  src/components/Background/index.tsx
  src/components/Background/style.ts
  src/components/TreeItem/index.tsx
  src/components/TreeItem/style.ts
  src/pages/tree/index.tsx
  src/pages/tree/style.ts
  src/types/TreeItemType.ts
Labels: 🎨 Type: Publishing

#10 :lipstick: Update register/login page style
  src/pages/login/index.tsx
  src/pages/login/style.ts
  src/pages/register/index.tsx
  src/pages/register/style.ts
Labels: 🎨 Type: Publishing

#11 PostModal, Tree 페이지 퍼블리싱 및 기능개발
  .gitignore
  package.json
  public/index.html
  src/App.tsx
  src/assets/svgs/Close.tsx
  src/atoms/state.ts
  src/components/PostModal/comentType/index.tsx
  src/components/PostModal/index.tsx
  src/components/PostModal/messageContent/index.tsx
  src/components/PostModal/style.ts
  src/components/ToastContainer/index.tsx
  src/index.tsx
  src/pages/commentPost/index.tsx
  src/pages/commentPost/style.ts
  src/pages/register/index.tsx
  src/pages/tree/index.tsx
  src/pages/tree/style.ts
  yarn.lock
Labels: ✨Type: feat, 🎨 Type: Publishing

#12 Update ViewModal
  src/components/Modal/PostModal/comentType/index.tsx
  src/components/Modal/PostModal/index.tsx
  src/components/Modal/PostModal/messageContent/index.tsx
  src/components/Modal/PostModal/style.ts
  src/components/Modal/ViewModal/index.tsx
  src/components/Modal/ViewModal/style.ts
  src/components/TreeItem/index.tsx
  src/pages/tree/index.tsx
Labels: ✨Type: feat, 🎨 Type: Publishing

#13 타이틀, 아이콘 추가 및 redirect 오류 수정
  netlify.toml
  package.json
  public/_redirects
  public/index.html
  public/star.ico
  src/API/TokenManager.ts
  src/API/index.ts
  src/API/tokenmanager.ts
Labels: ✨Type: feat, 🐛Type: fix

#16 Chunk 오류 해결
  public/index.html
  src/pages/tree/index.tsx
Labels: 🐛Type: fix

#17 delete toast container
  src/App.tsx
Labels: 🎨 Type: Publishing, 🐛Type: fix

#20 Tree페이지 수정 사항 수정
  public/index.html
  src/App.tsx
  src/pages/register/index.tsx
  src/pages/tree/index.tsx
Labels: ✨Type: feat
